# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IfHCWohgS1azDprjGj7GN59t2bBZehxm
"""

!pip install gradio

!pip install --upgrade gradio

def bubble_sort(arr):

  n=len(arr) #this is the length of the array, i.e. the number of integers in the list

  swapped = True #flag that sets swapped to true. "swapped" will help us log when two elements were swapped or not, in the end letting us know when the list is sorted

  while swapped == True:
    swapped = False

    for i in range(n-1): #in python we stop the loop one before, n would be one too long
      if arr[i] > arr[i+1]: #if the interger on the left side of the pair is greater than the one on the right:
        swapped = True #then they should be swapped
        arr[i], arr[i+1] = arr[i+1], arr[i] #this actually swaps their positions

  #when there are no more swap in a pass, then return the sorted array
  return arr

def bubble_sort_steps(arr):

  a = arr[:]       # work on a copy so original list stays untouched
  steps = []
  n = len(a)
  swapped = True

  #here we are trying to make a step by step list on how bubble sort works
  #we begin by adding the starting list as step 1
  steps.append(f"🫧 starting list: {a}\n")

  while swapped == True:
    swapped = False

    for i in range(n-1):

      if a[i] > a[i+1]:
        steps.append(f"🫧 compare {a[i]} and {a[i+1]}, since {a[i]} is greater than {a[i+1]} we swap!")
        swapped = True
        a[i], a[i+1] = a[i+1], a[i]
      else:
        steps.append(f"🫧 compare {a[i]} and {a[i+1]}, since {a[i]} is not greater than {a[i+1]} we don't swap!")

      steps.append(f"🫧 new list: {a}\n")

  steps.append(f"🫧 finished! sorted list: {a}")
  return a, "\n".join(steps)

import gradio as gr
from gradio.themes.base import colors

light_purple = colors.Color(name="light_purple",
                            c50="#f2b3ea", c100="#f2b3ea",
                            c200="#f2b3ea", c300="#f2b3ea",
                            c400="#f2b3ea", c500="#f2b3ea",
                            c600="#f2b3ea", c700="#f2b3ea",
                            c800="#6c3d91", c900="#4f276a", c950="#4f276a")

def sort_input_numbers(input_numbers):
  if not input_numbers.strip():
    msg = "Please make sure to enter your numbers!"
    return msg, msg

  try:
    parts = input_numbers.replace(",", " ").split()
    nums = [int(x) for x in parts]
  except ValueError:
    msg = "Please make sure to enter only numbers separated by spaces or commas!"
    return msg, msg

  # get BOTH sorted list + steps from bubble_sort_steps
  sorted_nums, explanation = bubble_sort_steps(nums)

  sorted_str = " ".join(str(x) for x in sorted_nums)

  return sorted_str, explanation




theme=gr.themes.Soft(
    primary_hue=light_purple, secondary_hue="sky",
    font=[gr.themes.GoogleFont("Baloo 2")],
    font_mono=[gr.themes.GoogleFont("Baloo 2")],
).set(
    body_background_fill="radial-gradient(circle, white, white, white, #b3e1f2, #f2b3ea, white)",
    body_background_fill_dark="radial-gradient(circle, white, white, white, #b3e1f2, #f2b3ea, white)",
    block_background_fill="white",
    block_background_fill_dark="white",
    block_shadow="none",
    input_background_fill="#b3e1f2",
    input_background_fill_dark="#b3e1f2",
    input_shadow="none",
    button_primary_background_fill="white",
    button_primary_background_fill_dark="white",
    button_primary_text_color="#f2b3ea",
    button_primary_text_color_dark="#f2b3ea",
    button_primary_shadow="none",
    button_primary_text_color_hover="white",
    button_primary_text_color_hover_dark="white",
)
with gr.Blocks() as demo:
  gr.Markdown("#  🫧   🫧   🫧   Bubble Sort   🫧   🫧   🫧 \n ## Unsorted list of numbers? \n ## Enter them below!")

  #input
  integer_input = gr.Textbox(label = "Enter the numbers you wish to be sorted here!")

  #output
  sorted_list = gr.Textbox(label = "Here is your sorted list!")

  #explanation box
  explanation_box = gr.Textbox(label = "Here is an explanation of how the algorithm works!", lines=15)

  #click to sort
  sort_button = gr.Button("🫧 Click to sort! 🫧", variant="primary")

  sort_button.click(fn = sort_input_numbers, inputs = integer_input, outputs = [sorted_list, explanation_box])

demo.launch(theme=theme)